### PR TITLE
Added a new mixer: ```Ridge Regression```

### PR DESCRIPTION
**Pull request by ma1VAR3**
The documentation for ridge regression can be found [here](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html#sklearn.linear_model.Ridge)

### CODE REVIEW

**Comment by George3d6** [comment]
The tests here seem to be failing due to formatting issues (limiting with flake8, you can replicate this by installing flake8 via pip and inside the lightwood directory running falke8)

Please check why the other PRs are failing, test logs should be fairly explicit.

**Comment by ma1VAR3** [comment]
Can you give me few more days please? I have exams going on right now, will get back at it and resolve these issues.

**Comment by George3d6** [comment]
In regards to hacktoberfest participation, that event is now closed... but if you want to finish the PRs regardless, you can take as much time as you'd like.

I generally close inactive PRs after 1-2 weeks but even then, you can always reopen them if you get the time to finish them.

**Comment by George3d6** [comment]
Closing as inactive for now.

**Pull request closed without merging**
