### PR TITLE
Update README.md example

### PR DESCRIPTION
**Pull request by ZoranPandovski**
We have an issue reported that the Lightwood basic example is not working https://github.com/mindsdb/mindsdb/issues/1750. This PR resolves the issue

### CODE REVIEW

**Comment by abitrolly** [comment]
Why not include the link to the Colab as well?

https://colab.research.google.com/drive/17HbZY2C0tme6YNkzyntb1OSwK52y4DxN?usp=sharing

**Comment by abitrolly** [comment]
@hakunanatasha so, how about the Colab link in README?

**Comment by ZoranPandovski** [comment]
Good idea @abitrolly, the current collab that I have shared is on my personal account so we will create a new one and include that in the README :raised_hands:

**Comment by abitrolly** [comment]
@ZoranPandovski the idea is not mine. The link is present in [archived `mindsb` `README.md`](https://github.com/mindsdb/mindsdb_native#usage) and was created by @George3d6.

**Comment by ZoranPandovski** [comment]
Anyway, thanks for pointing this out.

**Pull request merged**
