### PR TITLE
Implement a RandomForest mixer

### PR DESCRIPTION
**Pull request by jaredc07**
Hi @paxcema ,

I've implemented the first version #1005. 

1. implemented the RandomForest mixer: `lightwood/mixer/random_forest.py` 
2. integrated the RandomForest mixer to JsonAI `lightwood/api/json_ai.py`
3. and write a unit test `lightwood/test/unit_tests/mixer/test_random_forest.py`.

I will keep testing and improving.

### CODE REVIEW

**Review by paxcema — CHANGES_REQUESTED** [review]
There's a few changes that need to happen for `flake8` linting to pass without warnings (full list [here](https://github.com/mindsdb/lightwood/actions/runs/3242259956/jobs/5317780731)):

```python
./lightwood/mixer/random_forest.py:1:1: F401 'time' imported but unused
./lightwood/mixer/random_forest.py:8:1: F401 'sklearn.metrics.r2_score' imported but unused
./lightwood/mixer/random_forest.py:8:1: F401 'sklearn.metrics.accuracy_score' imported but unused
./lightwood/mixer/random_forest.py:9:1: F401 'typing.List' imported but unused
./lightwood/mixer/random_forest.py:9:1: F401 'typing.Set' imported but unused
./lightwood/mixer/random_forest.py:9:1: F401 'typing.Optional' imported but unused
./lightwood/mixer/random_forest.py:75:13: E722 do not use bare 'except'
./lightwood/mixer/random_forest.py:92:29: E126 continuation line over-indented for hanging indent
./lightwood/mixer/random_forest.py:104:97: E128 continuation line under-indented for visual indent
./tests/unit_tests/mixer/test_random_forest.py:6:1: F811 redefinition of unused 'ProblemDefinition' from line 5
```

**Review by paxcema — APPROVED** [review]
Amazing work @jaredc07! 

I see you have a couple of points for improvement. We can certainly tackle them as separate issues so that this can get merged straight away. I'm sure it will be very useful for a lot of users, thanks for your contribution! :)

**Comment by ZoranPandovski** [comment]
Awesome, thanks @jaredc07

**Comment by jaredc07** [comment]
> Amazing work @jaredc07!
> 
> I see you have a couple of points for improvement. We can certainly tackle them as separate issues so that this can get merged straight away. I'm sure it will be very useful for a lot of users, thanks for your contribution! :)

Thanks. It's my pleasure to make a contribution.

**Pull request merged**
