### PR TITLE
Improvements to Travis

### PR DESCRIPTION
**Pull request by ritwik12**
* Ignore Doc change #109
* Fail travis build for errors in scripts (unit tests) #110

@George3d6 This is just the same replication from mindsdb/mindsdb and I think will be useful as I was going through Lightwood

### CODE REVIEW

**Comment by George3d6** [comment]
We need to figure out why the OSX tests is failing, a similar thing was happening to mindsdb. Could the `set -e` not work on OSX ?

The logs themselves say "timeout" but the tests didn't run for very long ( less than 4 minutes).

Any ideas @ritwik12 ?

**Comment by ZoranPandovski** [comment]
The problem that we have found with -e also is that it exits immediately if a simple command exits with a non-zero status, and there are no additional logs from inside Travis.

**Comment by ritwik12** [comment]
@ZoranPandovski  That'll be natural I guess. I suggest using pytest instead of running scripts.

**Comment by ritwik12** [comment]
```
My build fails unexpectedly #

One possible cause for builds failing unexpectedly can be calling set -e (also known as set errexit), either directly in your .travis.yml, or sourceing a script which does. This causes any error causing a non-zero return status in your script to stop and fail the build immediately.

Note that using set -e in external scripts does not cause this problem, as the errexit is effective only in the external script.
```
For further details
https://docs.travis-ci.com/user/common-build-problems/

**Comment by ritwik12** [comment]
@George3d6 I guess`set -e` breaks in Linux.
https://github.com/travis-ci/docs-travis-ci-com/issues/1672

**Comment by ritwik12** [comment]
As suggested in above docs. We can use `set +e` later at some point based on the requirements of mindsdb

**Comment by George3d6** [comment]
@ritwik12  I'll just remove the `set -e` for now and make sure to throw errors whenever our test scripts fail.

**Comment by ritwik12** [comment]
@George3d6 Thanks, that will be great!!

**Pull request merged**
